Trimming searched items and can show/hide own subjects in results
slashwarm/elte-orarend pull request #10
Opened 2024-09-01 21:21 UTC by palyikris

When searching for course codes or names, the program removes all spaces from before and after the searched string. Implemented code in the results Calendar, that can show and hide your own subjects in it, so that you can see where you have collisions in the results and which ones can you add to your own calendar

2024-09-04 06:56 UTC, slashwarm approved these changes

2024-09-04 07:06 UTC, slashwarm requested changes

2024-09-05 16:13 UTC, slashwarm approved these changes
Szép PR, köszönöm szépen!

2024-09-05 16:13 UTC, merged

2024-09-05 16:25 UTC, palyikris commented
Én köszönöm!

On Thu, Sep 5, 2024 at 6:13 PM Gérnyi Márk ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Szép PR, köszönöm szépen!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/slashwarm/elte-orarend/pull/10#pullrequestreview-2283531376>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT3MTA5SGUC2P74SDZHPXIDZVB7LNAVCNFSM6AAAAABNPFOMH6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOBTGUZTCMZXGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>